apiVersion: v1
kind: Service
metadata:
  name: cloud-native-microservice
  labels:
    app: cloud-native-microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: cloud-native-microservice
