apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloud-native-microservice-prod

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml

labels:
  - pairs:
      environment: production
    includeSelectors: true

replicas:
  - name: cloud-native-microservice
    count: 3

images:
  - name: cloud-native-microservice
    newName: myacr.azurecr.io/cloud-native-microservice
    newTag: latest
