apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloud-native-microservice
  namespace: cloud-native-microservice
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloud-native-microservice
